### ISSUE TITLE
Prove the structure of the application and add missing dependencies

### ISSUE THREAD

**Issue by ZengineChris** [ZengineOrg/website#1]
At the moment jade is the template engine. We can also use another. For the styles i think sass. We can discuss about a javascript framework.

**Comment by Molasch** [comment]
Which JS framework would you prefer? Until now I have just worked with JQuery, but I don't think that this would be the right one for the website. What about Angular? The Qualytime is build with Angular, so maybe we would have a better recall value.

**Comment by ZengineChris** [comment]
@ZengineJulia want a blogging feature, so we are near a decision to use ghost.

**Comment by Molasch** [comment]
I dont't know anything about ghost. So I can learn something new, this is good :)
