### ISSUE TITLE
Site structure

### ISSUE THREAD

**Issue by ZengineChris** [ZengineOrg/website#2]
Witch sites we are need? I think about something similar to this  

-home
-christian
    - ...
-julia
    - ...
...
-imprint

We are zengine and so each of us has his own path to do what ever he will. Did we need a contact page? I don't think so. Each of us can have his own contact methods or links on his path.

**Comment by Molasch** [comment]
I think it should be possible to contact zengine or single members of the team. I'm not sure whether it should be an email contact form or just a redirect to a social media page of the member. The question is what we expect from the website: Do we just want it to say "hello, here we are!" or do we want to generate new contracts?

**Comment by ZengineChris** [comment]
I think it is more like: "this is my website because it is my website". More like we have fun to develop this, less we have to make this to generate more contracts.

**Comment by ZengineChris** [comment]
After a little talk we have a suggestion. The current express app as a proxy and behind the path is everybody free to make stuff and thinks.

**Comment by Molasch** [comment]
Hm yes this sounds pretty good :)
